version: '3'
services:
    mysql:
        image: mysql
        container_name: bcommerce_db_1
        restart: always
        ports:
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: bcommerce
            MYSQL_USER: bcommerce_user
            MYSQL_PASSWORD: 39ry820hwefso
            MYSQL_ROOT_PASSWORD: fwkfjbirh3t387rhffF
        volumes:
            - mysql_storage:/var/lib/mysql
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: bcommerce_pma
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: fwkfjbirh3t387rhffF
    redis:
        image: redis
        container_name: bcommerce_redis_1
        restart: always
        environment:
            - REDIS_PASSWORD=ahfifhr8239rrd
        ports:
            - '6379:6379'
volumes:
    mysql_storage:
